runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: 2.7.11

handlers:
- url: /favicon.ico
  static_files: app/static/favicon.ico
  upload: app/static/favicon.ico
  secure: always
- url: /static
  static_dir: app/static
  secure: always
- url: /.*
  script: run.app
  secure: always
